[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
anthropic = "0.0.8"
axum = { version = "0.8.1", features = ["multipart", "ws"] }
axum-extra = { version = "0.10.1" }
axum-server = { version = "0.7.2", features = ["tls-rustls"] }
axum_typed_multipart = "0.15.1"
futures = "0.3.31"
openssl = { version = "0.10.71", features = [
	"vendored",
] } # This is more docker environment
project-root = "0.2.2"
reqwest = { version = "0.12.12" }
rustls = { version = "0.23", features = ["ring"] }
scraper = "0.22.0"
serde = "1.0.217"
serde_json = "1.0.138"
sqlx = { version = "0.8.3", features = [
	"uuid",
	"postgres",
	"runtime-tokio",
	"tls-native-tls",
	"chrono",
] }
sysinfo = "0.33.1"
thirtyfour = { version = "0.35.0" }
tokio = { version = "1.43.0", features = ["full"] }
tokio-cron-scheduler = { version = "0.13.0", features = ["english"] }
tower-http = { version = "0.6.2", features = [
	"fs",
	"trace",
	"compression-br",
	"compression-deflate",
	"compression-gzip",
] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
uuid = { version = "1.16.0", features = ["v4"] }
utils = { path = "./utils" }
model = { path = "./model" }

[workspace]
members = ["utils", "model", "."]
